services:
  - type: web
    name: n8n
    env: docker
    region: oregon
    plan: starter
    branch: main
    numInstances: 1
    healthCheckPath: /
    envVars:
      - fromGroup: n8n-secrets

      # Static config values only (variables resolved via environment group)
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_SCHEMA
        value: public
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "false"
      - key: GENERIC_TIMEZONE
        value: America/Sao_Paulo
      - key: TZ
        value: America/Sao_Paulo
      - key: N8N_LOG_LEVEL
        value: info
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "168"
      - key: EXECUTIONS_DATA_SAVE_ON_ERROR
        value: all
      - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
        value: none
      - key: EXECUTIONS_DATA_SAVE_ON_PROGRESS
        value: "false"
      - key: EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS
        value: "false"
      - key: N8N_METRICS
        value: "true"
